# Generated by Django 2.1.4 on 2019-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_articlemoreinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='suffix',
            field=models.CharField(max_length=32, unique=True, verbose_name='个人博客后缀'),
        ),
    ]
