# Generated by Django 2.1.4 on 2019-03-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20190306_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Blog', verbose_name='所属博客'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo', verbose_name='文章作者'),
        ),
    ]
